[package]
name = "research-project-testing"
version = "0.1.0"
authors = ["Yoeri Otten <y.d.otten@student.utwente.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.19"
